### ISSUE TITLE
Codesign + Notarization

### ISSUE THREAD

**Issue by iambenmitchell** [carlosonunez/obs-installer-for-apple-silicon#2]
It would be cool if this script could also code sign the app and then perform notarization if there is a developer account present :) -- this is already a feature in the main OBS script.

**Comment by carlosonunez** [comment]
Hey, Ben. I finally took a look into this. The [CI build scripts](https://raw.githubusercontent.com/obsproject/obs-studio/cf518f4944df6ea1e42f0919b2718b3118582875/.github/workflows/main.yml) that OBS are using demonstrate how to notarize the apps. Since I don't have a developer account, I won't be able to do this. However, PRs are encouraged!
