### ISSUE TITLE
Alternative to this Script (WIP CI Build for Download on Official OBS Studio Repository)

### ISSUE THREAD

**Issue by chrisspiegl** [carlosonunez/obs-installer-for-apple-silicon#41]
Current development on the native OBS version continues and right now it is already possible to download a CI build version of the OSB-Studio GitHub Repository.

Todo so, you can go to the GitHub [Actions on the OBS Studio Repo](https://github.com/obsproject/obs-studio/actions/workflows/main.yml?query=branch%3Auniversal-build+actor%3APatTheMav).

There you can choose the latest successful build and click on that, there you will find the `Artifacts` and there you can download the `obs-macos-arm64` bundle which is almost like downloading the OBS Studio from the releases section of the GitHub Repo.

Only thing is that you will most likely have to `Right Click => Open` the DMG as well as on first launch the App itself (once you have it in your Applications folder). This is because the CI does not seem to codesign all the necessary things.

I hope this helps so you don't actually have to install all the dependencies which this `install.sh` script downlods.

I appreciate the work @carlosonunez has done here, I just want to share what I found when looking for a build of M1 OBS as of now.

**Comment by chrisspiegl** [comment]
P.S.: the currently latest CI Build for arm64 also supports Browser Sources already.

And it's running at about half the CPU needs of OBS through Rosetta.

**Comment by carlosonunez** [comment]
This is EXCELLENT news. Thank you so much, Chris.

I’ll update install.sh to solely download this release today. Once it becomes publicly-available on the Releases page, I will deprecate this project.

**Comment by Elyx0** [comment]
@carlosonunez Did today happen?

**Comment by Elyx0** [comment]
<img width="1174" alt="a8c2c4f37dfb3005558f81418876f9e4" src="https://user-images.githubusercontent.com/706218/147867664-2e6729ec-3945-48e2-bfa9-a4aa49591eb4.png">
Well I actually WAS blind.

**Comment by chrisspiegl** [comment]
Glad you could find it. I'm looking forward to the first official release and for all the plugins to pull up as well.

At the moment, things like NDI, WebSockets, and similar don't work or at least I have not gotten these two to work.

**Comment by carlosonunez** [comment]
I was finally able to get around to this!

So this actually isn't as official as it might seem. These builds are being produced by a forked version of the CI build script maintained [here](https://github.com/PatTheMav/obs-studio/tree/universal-build). The PR that merges these patches into the official project [hasn't been merged yet](https://github.com/obsproject/obs-studio/pull/5155).

Given this, `install.sh` v1.2.0 will allow you to download these artifacts by setting environment variable `USE_EXPERIMENTAL_UNIVERSAL_BUILD` to `true`.

Because we are downloading directly from GitHub Actions, you'll need to create a GitHub App with `read-only` permission to the GitHub Actions API. Go [here](https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app) to learn how to do that. After creating your app, provide `install.sh` with its credentials by setting `GH_CLIENT_ID` and `GH_CLIENT_SECRET` to your app's client ID and secret, respectively.

**Comment by washburnello** [comment]
Oh man, this is great! Thanks so much for working on this. It looks like the Move scene transition isn't showing up so I can't use it for now but I'll definitely keep my eyes on this going forward. :)
