### ISSUE TITLE
Plugins not working (Refer to MMdisc from Reddit's M1 Plugins)

### ISSUE THREAD

**Issue by FieryEarth** [carlosonunez/obs-installer-for-apple-silicon#7]
I had some M1 OBS plugins compiled by MMdisc on reddit, they worked great on his version of OBS. But they don't work on this one.

**Comment by carlosonunez** [comment]
That’s really interesting. Do you have a stack trace from one of your plugins that I can use to troubleshoot this?

**Comment by FieryEarth** [comment]
https://www.reddit.com/r/obs/comments/njwbxl/compiling_obs_for_apple_silicon_m1/h2dw750/?context=3

check that thread, MMdisc uploaded both his OBS version and his M1 optimized plugins.

**Comment by FieryEarth** [comment]
With my very limited knowledge of how these things work, I have identified that the plugin installers use Library/Application Support/obs-studio/plugins. However, your version of OBS doesn't load the settings from there. I can delete the whole obs-studio folder in application support and it doesn't affect the stuff on your version.

**Comment by FieryEarth** [comment]
Yeah, the default version and MMDisc versions of OBS install to all users, where as your version puts the settings under USERS/Username/Library/Application Support instead.

**Comment by FieryEarth** [comment]
copying over application support from all users to specific user doesn't seem to be enough to get the plugins working. I will keep testing different theories.

**Comment by FieryEarth** [comment]
This seems to make it work (suggested by MMdisc as a workaround, but supposedly there is a better way to approach it):

%sudo ln -s /opt/homebrew/Cellar/qt@5/5.15.2/Frameworks/QtWidgets.framework /Library/Frameworks/QtWidgets.framework
%sudo ln -s /opt/homebrew/Cellar/qt@5/5.15.2/Frameworks/QtGui.framework /Library/Frameworks/QtGui.framework
%sudo ln -s /opt/homebrew/Cellar/qt@5/5.15.2/Frameworks/QtCore.framework /Library/Frameworks/QtCore.framework

**Comment by willyk0** [comment]
The MMdisc's plugins you downloaded link to libraries placed in other subdirectories, that's why they don't work for this build. I compiled a couple of plugins and I needed to change cmake settings to point to the right place. Perhaps the cleanest solution is to compile them yourself (not harder that symlinking everything).

**Comment by carlosonunez** [comment]
Based on [this](https://github.com/carlosonunez/obs-installer-for-apple-silicon/issues/7#issuecomment-871023168) comment of yours, it appears that you need the Qt library for one of your plugins. This build does not include Qt; I believe this is also the limiting factor behind why an official ARM-compatible version doesn't exist yet.

I would recommend compiling OBS yourself or waiting for the OBS developers to make an official version available.

Since no work is needed on my part, I am going to close this issue. I'm all open for idea, however. Comment here if you have any, and I'll see what I can incorporate into this source code!

**Comment by fabltd** [comment]
I am running into a related issue. No matter what I do I cannot get plugs to load. Where should plugs be located?
